### ISSUE TITLE
Module 4

### ISSUE THREAD

**Issue by ASlivets** [ssimanich/GoJava#1]
Нужно внимательно перечатать [codeconventions] (http://www.oracle.com/technetwork/java/codeconventions-150003.pdf) и возможно пересмотреть [Часть 3. Как правильно называть переменные и выражения"] (https://app.schoology.com/page/454254235). Почему переменные с большой буквы? 
Вот наше задание:
1. Создать **класс**, вычисляющий площадь простых геометрических фигур: треугольника, прямоугольника и круга.
2. Создать **класс** преобразующий значение температуры по шкале Цельсия в значение по шкале Фаренгейта и в обратном направлении.
3. Создать **класс** вычисляющий расстояние между двумя точками, представленными координатами в двумерном пространстве (x1, y1), (x2, y2).
  
Для решения каждого подзадания к модулю нужно создать по 1 классу. В этих классах должны быть методы решающие определеныне задачи (нахождение площади, растояния и т.д.).
**P.S.** Было бы неплохо иметь в "корне" проекта одну папочку **src** а в ней все модули, например, как у [Егора] (https://github.com/EgorSalenko/GoITBasic) или у [Жени] (https://github.com/jonni21/GoJavaOnline).

**Comment by ssimanich** [comment]
https://github.com/ssimanich/src/tree/master/M4
